language: java

jdk: oraclejdk8

script: 
    ./mvnw test
  
after_success:
      - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
      - if [[ "$TRAVIS_BRANCH" = "develop" ]]; then git push -f https://:$HEROKU_TOKEN@git.heroku.com/gitproject.git develop; fi;
