language: java

jdk: oraclejdk8

script: 
    ./mvnw test
  
after_success:
      - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
      
deploy:
  provider: heroku
  api_key: c386c51c-57c0-4dea-9b60-5aa6e1cbef3e
  on: develop
