language: java

jdk: oraclejdk8

script: 
    ./mvnw test
  
after_success:
      - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
      
deploy:
    provider: heroku
     api_key: 
         secure: 17992561-ef8e-4463-9d5e-1f9fab308153
     on : develop
